"""empty message

Revision ID: d5d277664303
Revises: 4f3b43f20a6e
Create Date: 2017-05-29 09:58:21.642802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d277664303'
down_revision = '4f3b43f20a6e'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_avatar', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'real_avatar')
    ### end Alembic commands ###
